[versions]
agp = "8.6.0-alpha02"
androidx-activityCompose = "1.9.0"
compose-plugin = "1.6.10-rc03"
kotlin = "2.0.0-RC3"
coil = "3.0.0-alpha06"
fuel-kotlinx-serialization = "3.0.0-alpha1"
kotlinx-datetime = "0.6.0"
buildkonfig = "0.15.1"
kotlinxCollectionsImmutable = "0.3.7"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
coil-network = { group = "io.coil-kt.coil3", name = "coil-network-core", version.ref = "coil" }
coil = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
fuel-kotlinx-serialization = { group = "com.github.kittinunf.fuel", name = "fuel-kotlinx-serialization", version.ref = "fuel-kotlinx-serialization" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxCollectionsImmutable" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinPluginSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }